name: CI

on:
  push:
    branches: [develop]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Deploy candy calculator
      run: |
        cd $GITHUB_WORKSPACE
        git checkout develop
        mkdir pokemon-exp-candy
        cd candy-calculator
        npm install elm@latest-0.19.1
        npm install create-elm-app
        elm-app build
        mv build/* ../pokemon-exp-candy
    - name: Commit files
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -am "Add changes"
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force: true
