name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Elm environment
      uses: JorelAli/setup-elm@v1
    - uses: actions/checkout@v1
      with:
        submodules: true
    - name: Deploy candy calculator
      run: |
        cd $GITHUB_WORKSPACE
        mkdir pokemon-exp-candy
        cd candy-calculator
        elm make src/Main.elm --output="../pokemon-exp-candy/index.html"
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@3.0.3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BASE_BRANCH: master # The branch the action should deploy from.
        BRANCH: gh-pages # The branch the action should deploy to.
        FOLDER: pokemon-exp-candy # The folder the action should deploy.
