name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Elm environment
      uses: JorelAli/setup-elm@v1
    - name: Deploy candy calculator
      run: |
        mkdir pokemon-exp-candy
        cd candy-calculator
        elm make src/Main.elm --output="../pokemon-exp-candy/index.html"
