name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Elm environment
      uses: JorelAli/setup-elm@v1
    - uses: actions/checkout@v1
      with:
        submodules: true
        token: ${{ secrets.GitHub_PAT }}
    - name: Deploy candy calculator
      run: |
        cd $GITHUB_WORKSPACE
        mkdir pokemon-exp-candy
        cd candy-calculator
        elm make src/Main.elm --output="../pokemon-exp-candy/index.html"
